session:
    email: crt@crt.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNydEBjcnQuY29tIiwiZXhwIjoxNzU4NTU3NzQxLCJpYXQiOjE3NTgyOTg1NDF9.bkAFTeD1XDA_HGJzhgV_JCTnhGbAA24YiNOII4q7X_c
