session:
    email: crt@crt.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNydEBjcnQuY29tIiwiZXhwIjoxNzU4NzI4NTAxLCJpYXQiOjE3NTg0NjkzMDF9.FvMdhxgqrLn5X-zarrXWXvqQO53g68soI4s2VGc2p9I
